language: php
dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0
    - COMPOSER_MEMORY_LIMIT=-1

jobs:
  include:
    - stage: test
      name: 'Test installing the lowest dependencies'
      php: 7.2
      install:
        - composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit
        - php vendor/bin/phpstan analyse src tests --level=7

    - stage: test
      php: 7.2
      install:
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit
        - php vendor/bin/phpstan analyse src tests --level=7

    - stage: test
      php: 7.3
      install:
        - composer update --no-interaction --no-suggest
      script:
        - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
        - php vendor/bin/phpstan analyse src tests --level=7
      after_script:
        - php vendor/bin/php-coveralls -o coveralls-upload.json -x coverage.xml

    - stage: test
      if: 'type = cron'
      php: 7.4snapshot
      install:
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit
        - php vendor/bin/phpstan analyse src tests --level=7

    # Ignore the platform requirements for the upcoming PHP version
    - stage: test
      if: 'type = cron'
      php: nightly
      install:
        - composer update --ignore-platform-reqs --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit
        - php vendor/bin/phpstan analyse src tests --level=7

  allow_failures:
    - php: 7.4snapshot
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer global require symfony/flex
